In [2]:
import pandas as pd

In [5]:
executionDF = pd.read_csv("DPIC Execution Database - U.S. Executions.csv")

In [11]:
columns = executionDF.columns.tolist()
print(columns)

['Foreign National', 'Number of White Male Victims', 'Juvenile', 'First Name', 'Last Name', 'Middle Name(s)', 'Suffix', 'Race', 'Sex', 'Region', 'Country', 'State', 'Execution Date', 'Number of Victims', 'Number of Black Male Victims', 'Number of Latino Male Victims', 'Number of Asian Male Victims', 'Number of Native American Male Victims', 'Number of Other Race Male Victims', 'Number of White Female Victims', 'Number of Black Female Victims', 'Number of Latino Female Victims', 'Number of Asian Female Victims', 'Number of American Indian or Alaska Native Female Victims', 'Number of Other Race Female Victims', 'Victim(s) Race(s)', 'Race of Victims (Multiple races including white)']

In [13]:
executionDF.head()

,Foreign National,Number of White Male Victims,Juvenile,First Name,Last Name,Middle Name(s),Suffix,Race,Sex,Region,...,Number of Native American Male Victims,Number of Other Race Male Victims,Number of White Female Victims,Number of Black Female Victims,Number of Latino Female Victims,Number of Asian Female Victims,Number of American Indian or Alaska Native Female Victims,Number of Other Race Female Victims,Victim(s) Race(s),Race of Victims (Multiple races including white)
0,No,1,no,Gary,Gilmore,Mark,NaN,White,Male,West,...,0,0,0,0,0,0,0,0,White,White
1,No,1,no,John,Spenkelink,NaN,NaN,White,Male,South,...,0,0,0,0,0,0,0,0,White,White
2,No,1,no,Jesse,Bishop,NaN,NaN,White,Male,West,...,0,0,0,0,0,0,0,0,White,White
3,No,2,no,Steven,Judy,NaN,NaN,White,Male,Midwest,...,0,0,2,0,0,0,0,0,White,White
4,No,1,no,Frank,Coppola,NaN,NaN,White,Male,South,...,0,0,0,0,0,0,0,0,White,White

In [17]:
newExecutionDF = executionDF.drop(columns=["Middle Name(s)", "Suffix"])
newExecutionDF.head()

,Foreign National,Number of White Male Victims,Juvenile,First Name,Last Name,Race,Sex,Region,Country,State,...,Number of Native American Male Victims,Number of Other Race Male Victims,Number of White Female Victims,Number of Black Female Victims,Number of Latino Female Victims,Number of Asian Female Victims,Number of American Indian or Alaska Native Female Victims,Number of Other Race Female Victims,Victim(s) Race(s),Race of Victims (Multiple races including white)
0,No,1,no,Gary,Gilmore,White,Male,West,United States,Utah,...,0,0,0,0,0,0,0,0,White,White
1,No,1,no,John,Spenkelink,White,Male,South,United States,Florida,...,0,0,0,0,0,0,0,0,White,White
2,No,1,no,Jesse,Bishop,White,Male,West,United States,Nevada,...,0,0,0,0,0,0,0,0,White,White
3,No,2,no,Steven,Judy,White,Male,Midwest,United States,Indiana,...,0,0,2,0,0,0,0,0,White,White
4,No,1,no,Frank,Coppola,White,Male,South,United States,Virginia,...,0,0,0,0,0,0,0,0,White,White